# Generated by Django 2.1.4 on 2019-01-26 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TotalScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='sumanth', max_length=50)),
                ('sixthquestionanswer', models.IntegerField(default=0)),
                ('sixthquestionmarks', models.IntegerField(default=0)),
                ('seventhquestionanswer', models.IntegerField(default=0)),
                ('seventhquestionmarks', models.IntegerField(default=0)),
                ('totalmarks', models.IntegerField(default=0)),
                ('percentage', models.IntegerField(default=0)),
            ],
        ),
    ]
