# Generated by Django 2.1.4 on 2019-02-24 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examapp2', '0002_userprofileinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='totalscore',
            name='eigthquestionanswer',
            field=models.CharField(default='sumanth', max_length=300),
        ),
        migrations.AddField(
            model_name='totalscore',
            name='eigthquestionmarks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='totalscore',
            name='ninthquestionanswer',
            field=models.CharField(default='sumanth', max_length=300),
        ),
        migrations.AddField(
            model_name='totalscore',
            name='ninthquestionmarks',
            field=models.IntegerField(default=0),
        ),
    ]
