# Generated by Django 2.1.4 on 2019-02-24 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examapp2', '0003_auto_20190224_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totalscore',
            name='eigthquestionanswer',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='totalscore',
            name='ninthquestionanswer',
            field=models.CharField(max_length=300),
        ),
    ]
